// Single source of truth for the site's pages.
//
// Navigation is plain `<a href>` — there is no client-side router. Each route
// corresponds to one `.html` file in the project root, which Vite builds as its
// own document (see vite.config.ts).
//
// There are two kinds. Static pages are listed here and have a hand-written
// component in `src/pages/`. Variety pages are not listed at all: they are
// derived from `content/varieties/*.json`, and their documents and entries are
// generated by `scripts/gen-pages.mjs` before the build. Adding a product is
// adding a content file — this module picks it up with no edit.
//
// Hosts that serve `foo.html` at `/foo` (Netlify does) give clean URLs for
// free; the dev and preview servers are taught the same trick in vite.config.ts
// so all three environments behave identically.

import { varieties } from '../data/varieties'

export interface Route {
  /** URL path, extensionless. */
  path: string
  /** HTML entry filename, relative to the project root. */
  file: string
  /** Short label for navigation. */
  label: string
  /** Full label for breadcrumbs, footers and link titles. */
  title: string
}

/** Static pages — one hand-written component each, under `src/pages/`. */
export const routes = {
  home: { path: '/', file: 'index.html', label: 'Home', title: 'Home' },
  products: {
    path: '/products',
    file: 'products.html',
    label: 'Products',
    title: 'All varieties',
  },
  quality: {
    path: '/quality',
    file: 'quality.html',
    label: 'Quality',
    title: 'Quality & process',
  },
  packaging: {
    path: '/packaging',
    file: 'packaging.html',
    label: 'Packaging',
    title: 'Packaging & shipping',
  },
  about: { path: '/about', file: 'about.html', label: 'About', title: 'About MAVEH WORLD' },
  markets: {
    path: '/markets',
    file: 'markets.html',
    label: 'Markets',
    title: 'Export destinations',
  },
  contact: {
    path: '/contact',
    file: 'contact.html',
    label: 'Contact',
    title: 'Contact & request a quote',
  },
} as const satisfies Record<string, Route>

export type RouteKey = keyof typeof routes

/** Primary navigation, in order. */
export const primaryNav: RouteKey[] = [
  'home',
  'products',
  'quality',
  'packaging',
  'markets',
  'about',
]

/** Path for a variety's detail page. The slug is the URL. */
export function varietyPath(slug: string): string {
  return `/${slug}`
}

/** Document filename for a variety's detail page. */
export function varietyFile(slug: string): string {
  return `${slug}.html`
}

/**
 * Variety detail routes, in the order they appear across the site. Derived, so
 * a variety added through the admin turns up in the footer and the sitemap
 * without anyone remembering to register it.
 */
export const varietyRoutes: Record<string, Route> = Object.fromEntries(
  varieties.map((v) => [
    v.slug,
    { path: varietyPath(v.slug), file: varietyFile(v.slug), label: v.name, title: v.fullName },
  ]),
)

/** Every route that gets a prerendered document. Static pages first. */
export const allRoutes: Route[] = [...Object.values(routes), ...Object.values(varietyRoutes)]
