// @generated by scripts/gen-pages.mjs — do not edit.
// Generated from content/varieties/teja.json.
import '../styles'
import { mount } from './mount'
import { VarietyPage } from '../components/VarietyPage'
import { getVariety } from '../data/varieties'

const variety = getVariety('teja')
if (!variety) throw new Error('Unknown variety: teja')

mount(<VarietyPage variety={variety} />)
