// Generate variety pages — run with `npm run pages`, before `vite build`.
//
// A variety is a JSON document in `content/varieties/`. This script turns each
// one into the two files the build needs and neither the client nor the CMS
// should ever have to write by hand:
//
//   <slug>.html            the document — title, description, canonical, Open
//                          Graph and Product JSON-LD, all from the data
//   src/entries/<slug>.tsx the client entry that hydrates it
//
// Both are marked @generated and are rewritten on every build. Files carrying
// that marker whose variety no longer exists are deleted, so removing a product
// in the admin removes its page rather than orphaning it.
//
// They are committed rather than ignored: a fresh clone should be able to run
// `npm run dev` without a build step first, and `git status` showing the page
// set is a feature when the CMS is what adds to it.
//
// The variety data is loaded through Vite rather than parsed here, so the
// normalisation, validation and SEO fallbacks in src/data/varieties.ts are the
// only copy of those rules.

import { createServer } from 'vite'
import { readdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const ENTRIES = resolve(ROOT, 'src/entries')

const MARK_HTML = '<!-- @generated by scripts/gen-pages.mjs — do not edit. -->'
const MARK_TSX = '// @generated by scripts/gen-pages.mjs — do not edit.'

/** Escape for use inside an HTML attribute or text node. */
const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')

/**
 * Product JSON-LD.
 *
 * Only fields with a value are emitted. ASTA colour and aflatoxin are null
 * until the client supplies figures, and an empty PropertyValue in structured
 * data is worse than an absent one — it asserts the property exists and is
 * blank.
 */
function productJsonLd(variety, company, url) {
  const property = (name, value) => ({ '@type': 'PropertyValue', name, value })

  const properties = [
    property('Scoville heat units', `${variety.shuLabel} SHU`),
    property('Moisture', variety.moisture),
    property('Foreign matter', variety.foreignMatter),
    property('HSN code', variety.hsn),
  ]
  if (variety.astaColour) properties.push(property('ASTA colour', variety.astaColour))
  if (variety.aflatoxin) properties.push(property('Aflatoxin', variety.aflatoxin))

  return {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: `${variety.fullName} Dry Red Chilli`,
    category: 'Dry red chilli',
    description: variety.summary,
    url,
    brand: { '@type': 'Brand', name: company.name },
    additionalProperty: properties,
  }
}

function documentFor(variety, company, origin) {
  const url = `${origin}/${variety.slug}`
  const { title, description, ogDescription } = variety.seo

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#0B1236" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />

    ${MARK_HTML}
    <!--
      Generated from content/varieties/${variety.slug}.json. Edit that file — or
      the variety in /admin — not this document.

      This route is its own document. Its title, description, canonical and Open
      Graph tags are static here rather than written at runtime, and the page
      body is prerendered into #root by scripts/prerender.mjs — so nothing on
      this page depends on JavaScript having run.
    -->
    <title>${esc(title)}</title>
    <meta name="description" content="${esc(description)}" />
    <link rel="canonical" href="${esc(url)}" />

    <meta property="og:type" content="product" />
    <meta property="og:site_name" content="${esc(company.name)}" />
    <meta property="og:url" content="${esc(url)}" />
    <meta property="og:title" content="${esc(title)}" />
    <meta property="og:description" content="${esc(ogDescription)}" />
    <!-- TODO: per-variety 1200x630 share image, once real product photography exists. -->
    <meta property="og:image" content="${esc(origin)}/og-default.svg" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta name="twitter:card" content="summary_large_image" />

    <!--
      Scroll reveals start hidden. That start state is applied here, not in the
      prerendered markup, so this page is readable without JS. Reduced motion
      opts out entirely, and the timeout drops the start state if the bundle
      never arrives rather than leaving content invisible.
    -->
    <script>
      ;(function () {
        try {
          if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return
          var el = document.documentElement
          el.classList.add('js-reveal')
          setTimeout(function () {
            if (!el.classList.contains('hydrated')) el.classList.remove('js-reveal')
          }, 4000)
        } catch (e) {}
      })()
    </script>

    <script type="application/ld+json">
${JSON.stringify(productJsonLd(variety, company, url), null, 2)
  .split('\n')
  .map((line) => `      ${line}`)
  .join('\n')}
    </script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/entries/${variety.slug}.tsx"></script>
  </body>
</html>
`
}

function entryFor(variety) {
  return `${MARK_TSX}
// Generated from content/varieties/${variety.slug}.json.
import '../styles'
import { mount } from './mount'
import { VarietyPage } from '../components/VarietyPage'
import { getVariety } from '../data/varieties'

const variety = getVariety('${variety.slug}')
if (!variety) throw new Error('Unknown variety: ${variety.slug}')

mount(<VarietyPage variety={variety} />)
`
}

/**
 * Write only when the content differs.
 *
 * These files are committed, and rewriting an identical file on every build
 * would touch its mtime, which is enough to make Vite's dev server reload and
 * to litter `git status` on a build that changed nothing.
 */
async function writeIfChanged(path, contents) {
  if (existsSync(path) && (await readFile(path, 'utf8')) === contents) return false
  await writeFile(path, contents, 'utf8')
  return true
}

/** Remove generated files for varieties that no longer exist. */
async function pruneStale(dir, keep, marker, suffix) {
  let removed = 0
  for (const name of await readdir(dir)) {
    if (!name.endsWith(suffix) || keep.has(name)) continue
    const path = resolve(dir, name)
    if (!(await readFile(path, 'utf8')).includes(marker)) continue
    await unlink(path)
    process.stdout.write(`  − ${name.padEnd(20)} removed, no such variety\n`)
    removed++
  }
  return removed
}

const server = await createServer({
  root: ROOT,
  logLevel: 'error',
  server: { middlewareMode: true },
  appType: 'custom',
})

try {
  const { varieties } = await server.ssrLoadModule('/src/data/varieties.ts')
  const { company } = await server.ssrLoadModule('/src/data/company.ts')
  const origin = String(company.siteUrl).replace(/\/$/, '')

  let written = 0
  for (const variety of varieties) {
    const html = await writeIfChanged(
      resolve(ROOT, `${variety.slug}.html`),
      documentFor(variety, company, origin),
    )
    const tsx = await writeIfChanged(
      resolve(ENTRIES, `${variety.slug}.tsx`),
      entryFor(variety),
    )
    const changed = html || tsx
    if (changed) written++
    process.stdout.write(
      `  ${changed ? '✓' : '·'} ${variety.slug.padEnd(20)} ${changed ? 'written' : 'unchanged'}\n`,
    )
  }

  const slugs = new Set(varieties.map((v) => v.slug))
  const removed =
    (await pruneStale(ROOT, new Set([...slugs].map((s) => `${s}.html`)), MARK_HTML, '.html')) +
    (await pruneStale(ENTRIES, new Set([...slugs].map((s) => `${s}.tsx`)), MARK_TSX, '.tsx'))

  process.stdout.write(
    `Generated ${varieties.length} variety page(s)` +
      `${written ? `, ${written} changed` : ', all unchanged'}` +
      `${removed ? `, ${removed} file(s) pruned` : ''}.\n`,
  )
} finally {
  await server.close()
}
